### ISSUE TITLE
Add plain /status endpoint

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-go#7]
This endpoint returns a 200 OK which is the most basic check for knowing the service is running.

**Comment by reinkrul** [comment]
Maybe the service should check on all engines if they're OK (and each engine should implement a check function)?

**Comment by woutslakhorst** [comment]
that would be /diagnostics
/status should be able to handle a request every second, where /diagnostics has a lower request rate and should be the source for more extensive monitoring tools.
